import type { Metadata } from "next";
import { Geist, Cherry_Swash } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/Nav";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist",
  subsets: ["latin"],
});

const cherrySwash = Cherry_Swash({
  variable: "--font-cherry",
  subsets: ["latin"],
  display: "swap",
  weight: "700",
});

export const metadata: Metadata = {
  title: {
    default: "TaleGenie",
    template: "%s | TaleGenie",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${cherrySwash.variable} font-geist grid grid-rows-[auto_1fr_auto] overflow-x-hidden antialiased`}
      >
        <NavBar />
        <main className="grid min-h-screen gap-20">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
